### ISSUE TITLE
Can't seem to run DateTime.test.tsx

### ISSUE THREAD

**Issue by JoaoTMDias** [NateRadebaugh/react-datetime#768] opened 2020-01-23 17:51 UTC
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

- Clone the repository
- Run npm install
- Run npm test

### Expected Results

- Passing tests with jest

### Actual Results

- Weird results like "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object." (see screenshot below)

### Minimal Reproduction of the Problem

- Just download the repo, install packages and try to run tests. They all (or at least most of them) seem to fail.
- I don't know if this is related to newer versions of jest or testing-library.
- Storybook runs fine, though.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)

Node version: 12.13.0
NPM version: 6.13.6
OS: MacOS 10.15.2

![Screenshot 2020-01-23 at 17 47 58](https://user-images.githubusercontent.com/2223881/73009790-1d92a900-3e09-11ea-9d55-6bc1b350fc46.png)
![Screenshot 2020-01-23 at 17 47 43](https://user-images.githubusercontent.com/2223881/73009805-24212080-3e09-11ea-8e11-68fb0a290cd5.png)
![Screenshot 2020-01-23 at 17 48 05](https://user-images.githubusercontent.com/2223881/73009785-19668b80-3e09-11ea-9deb-7a16037712ce.png)

**Comment by NateRadebaugh** [comment] 2020-01-23 18:08
Thanks @JoaoTMDias 

I've also seen this if I try to bump all the deps using `yarn upgrade`.

The tests are all passing in CircleCI, but we do see a ton of warnings around `act()`:
* https://circleci.com/gh/NateRadebaugh/react-datetime/2129?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Not sure which is the issue:
* https://github.com/reach/reach-ui
* https://github.com/testing-library/react-testing-library

**Comment by NateRadebaugh** [comment] 2020-01-23 18:46
This seems most likely to be something I'm doing wrong with the react-testing-library, but I'm not sure what's so wrong about it. @kentcdodds any ideas?

To (maybe related) issues here:
1. "expected a string but got: object"
2. Warnings around `act` not wrapping changes

The [events cheatsheet docs](https://testing-library.com/docs/react-testing-library/cheatsheet#events) seem to suggest my `fireEvent.click` doesn't need `act()`.
> React Testing Library wraps render and fireEvent in a call to `act` already so most cases should not require using it manually

The [FAQ](https://testing-library.com/docs/react-testing-library/faq) suggests I use `async` versions of the queries, but that didn't make a difference.

For reference, here's what I'm doing. 
```js
    it("should open day picker when clicking", () => {
      mockDate(new Date(2019, 0, 1, 12, 1, 12, 34));

      // Arrange
      const { getByLabelText } = render(
        <>
          <label htmlFor="some-id">Some Field</label>
          <DateTime id="some-id" dateFormat={FULL_DATE_FORMAT} />
        </>
      );

      // Act
      const element = getByLabelText("Some Field");
      fireEvent.click(element);

      // Assert
      const picker = getByTestId("day-picker");
      expect(picker).toBeVisible();
    });

    it("should open day picker on focus", () => {
      mockDate(new Date(2019, 0, 1, 12, 1, 12, 34));

      // Arrange
      const { getByLabelText } = render(
        <>
          <label htmlFor="some-id">Some Field</label>
          <DateTime id="some-id" dateFormat={FULL_DATE_FORMAT} />
        </>
      );

      // Act
      const element = getByLabelText("Some Field");
      fireEvent.focus(element);

      // Assert
      const picker = getByTestId("day-picker");
      expect(picker).toBeVisible();
    });
```

**Comment by kentcdodds** [comment] 2020-01-24 15:54
I don't have much time to look into this, but I have yet to find a situation where an `act` warning was wrong.

And 99% of the time when you're using React Testing Library utilities and you're still seeing warnings, it's because you've finished your test before your async code was finished.

For more on this, checkout the end of this post: https://kentcdodds.com/blog/write-fewer-longer-tests

Good luck!

**Comment by NateRadebaugh** [comment] 2020-01-25 03:39
I added a bunch of `await` to the code and put an `await wait()` in the `afterEach` and it seems to have fixed the issues with the warnings. With these changes, I was able to bump to latest version of deps and still see the tests pass without any warnings or errors.

See results in CircleCI.

@JoaoTMDias  can you try again with `master` and close if the issue is resolved for you?

**Comment by JoaoTMDias** [comment] 2020-01-26 16:38
Yes, thanks for all the feedback. Will try tonight and let you know :)

**Comment by NateRadebaugh** [comment] 2020-01-27 14:31
Closing. Re-open if you're still seeing issues.

**Closed by NateRadebaugh** 2020-01-27 14:31 UTC
